### PR TITLE
Access object and err by const ref

### PR DESCRIPTION
**Pull request by Dimon4eg**

### CODE REVIEW

**Comment by hellozee** [comment]
Honestly, I don't know, if I am good enough to review this PR, :smile: 
Though thanks for the patch, I would read about the stuff you did and check

Well, this shouldn't matter but if possible could you keep everything in snake_case?
I never thought someone would give a shit about it

**Comment by Dimon4eg** [comment]
Where is not camel case?

**Comment by hellozee** [comment]
@Dimon4eg ahh just ignore what I said, :laughing:

**Comment by Dimon4eg** [comment]
Okay, no problem man

**Comment by hellozee** [comment]
Okay, it does not compile, you forgot to include `#include <utility>` and `std::move` shouldn't throw exception at any cost, please use `std::move_if_noexcept `

**Comment by Dimon4eg** [comment]
Why it should not throw exceptions?
For example old copy constructor can throw exceptions.

**Comment by hellozee** [comment]
@Dimon4eg the purpose of writing this was to avoid the possibility of writing even a single try..catch, well

**Comment by Dimon4eg** [comment]
Really?
Why?

**Comment by hellozee** [comment]
Simple, I don't like them and I like the go's way more, :)

**Comment by Dimon4eg** [comment]
I see.
But you cannot guarantee no exception can happen because copy constructor you have wrote can throw exceptions ^_^
And move constructor usually should not throw because there should be no any memory allocations.
If you don't want to use exception you can off them.
Some info [here](https://stackoverflow.com/a/7249442/1792865)

**Comment by hellozee** [comment]
Heyy, I didn't write any copy constructor, XD

**Comment by Dimon4eg** [comment]
https://github.com/hellozee/errors/blob/2a148a9ffe379ba593c1dd290a8d9caf9be4f156/include/errors.h#L56

This actually not copy constructor but it calls copy constructor of `type`

**Comment by hellozee** [comment]
@Dimon4eg ahh, now I see it, :)

**Comment by Dimon4eg** [comment]
@hellozee will you merge the PR?

**Comment by hellozee** [comment]
@Dimon4eg sorry, it went out of my mind, :)

**Pull request merged**
